name       : foomatic-db-nonfree
version    : 20150819
release    : 1
source     :
    - http://www.openprinting.org/download/foomatic/foomatic-db-nonfree-20150819.tar.gz : f061e3bfa28d848c843d7562a490ac3a732b9b9ab313a69ea2729cc3f8a22a1f
license    :
    - Distributable
    - NonFree
summary    : Foomatic database extension consisting of manufacturer-supplied PPD files released under non-free licenses which restricts them in how they can get redistributed.
description: |
    Manfafacturer-supplied PPD files under non-free licenses
rundeps    :
    - foomatic-db
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
