name       : foomatic-db-nonfree
version    : '20170420'
release    : 2
source     :
    - https://solus-project.com/sources/printing/foomatic-db-nonfree-20170420.tar.gz : 3f016322d9519d7243d782189c170e6f33353c8d67c253741b7d11186cdc5163
license    :
    - Distributable
    - NonFree
component  : desktop.core
summary    : Foomatic database extension consisting of manufacturer-supplied PPD files released under non-free licenses which restricts them in how they can get redistributed.
description: |
    Manfafacturer-supplied PPD files under non-free licenses
rundeps    :
    - foomatic-db
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
