name       : foomatic-db-nonfree
version    : '20171010'
release    : 3
source     :
    - https://www.openprinting.org/download/foomatic/foomatic-db-nonfree-20171010.tar.gz : 2ba13b6d699a4ef36edddf7a869c977a2a964bfb0a71e3c7ad0c9551d2ac700c
license    :
    - Distributable
    - NonFree
component  : desktop.core
summary    : Foomatic database extension consisting of manufacturer-supplied PPD files released under non-free licenses which restricts them in how they can get redistributed.
description: |
    Manfafacturer-supplied PPD files under non-free licenses
rundeps    :
    - foomatic-db
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
