name       : foomatic-db-nonfree
version    : 4.0.20171217
release    : 4
source     :
    - https://www.openprinting.org/download/foomatic/foomatic-db-nonfree-20171217.tar.gz : 98a4074ddcb2ef5c990391cae34135ff9833829ea20caed10d8ef18a41be4ed5
license    :
    - Distributable
    - NonFree
component  : desktop.core
summary    : Foomatic database extension consisting of manufacturer-supplied PPD files released under non-free licenses which restricts them in how they can get redistributed.
description: |
    Manfafacturer-supplied PPD files under non-free licenses
rundeps    :
    - foomatic-db
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
